# Generated by Django 3.1.7 on 2022-02-07 09:10

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(max_length=256, storage=files.models.OverwriteStorage(), upload_to='files/')),
                ('is_valid', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[(1, 'Configuration file'), (2, 'Application or Program'), (3, 'Data file')], default=3, max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Files',
                'db_table': 'files',
                'ordering': ['title'],
            },
        ),
    ]
