# Generated by Django 3.1.7 on 2022-02-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Configuration file'), (2, 'Application or Program'), (3, 'Data file')], default=3),
        ),
    ]
