# Generated by Django 3.1.7 on 2021-09-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20210827_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationasset',
            name='is_asset',
            field=models.BooleanField(default=False),
        ),
    ]
