# Generated by Django 3.1.7 on 2021-09-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_operationasset_is_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationasset',
            old_name='is_asset',
            new_name='is_annex',
        ),
    ]
