# Generated by Django 3.1.7 on 2021-09-21 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_auto_20210921_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='designer.database', verbose_name='database'),
        ),
    ]
