# Generated by Django 3.1.7 on 2021-10-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_query_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='database',
        ),
        migrations.DeleteModel(
            name='Database',
        ),
    ]
