# Generated by Django 3.1.7 on 2021-10-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_auto_20211018_0935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueryForm',
        ),
    ]
