# Generated by Django 3.1.7 on 2022-02-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0006_query_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
